### ISSUE TITLE
Invalid parameters count

### ISSUE THREAD

**Issue by patrikmor** [TrevorPilley/MicroLite#393]
Example code:
```
using(var session = factory.OpenReadOnlySession())
{
    var sqlQuery = new SqlQuery("SELECT 1 FROM table WHERE column1 <> '' AND id = @p0 AND column2 <> ''", 1);
    var result = session.Fetch<int>(sqlQuery);
}
```
Throws exception: _Must declare the scalar variable "@p0"._
Problem is in class __SqlUtility__ method __GetParameterPosition__ in part "Ignore identifiers inside a quoted string." where is incorect detection of quotes before and after parameter name.

**Comment by TrevorPilley** [comment]
I'll have a look as soon as I get the chance - open to a PR if you want to have a go at fixing it or a failing test

**Comment by TrevorPilley** [comment]
As a work around, does it work correctly if you do the id = @p0 as the first condition?

**Comment by patrikmor** [comment]
Yes, but the code was only example. In my case I have multiple selects using Include functionality, so command text is merged from all commands (MsSQL) and in renumbering of parameters it incorectly detects parameter name in quotes. (I have quotes in some selects).

**Comment by TrevorPilley** [comment]
OK, I'll look at it when I can.

What are you using the quotes for? you can (and possibly should) parameterise those too:

```csharp
var sqlQuery = new SqlQuery(
    "SELECT 1 FROM table WHERE column1 <> @p0 AND id = @p1 AND column2 <> @p0",
    string.Empty, 
    1);
```
