### ISSUE TITLE
IsEqualTo(null) should mean the same as IsNull()

### ISSUE THREAD

**Issue by djanosik** [TrevorPilley/MicroLite#395]
I think `IsEqualTo(null)` should generate the same SQL query as `IsNull()`. It would make it easier to build complex SQL queries.

**Comment by TrevorPilley** [comment]
Good idea, feel free to submit a pull request with that in if you fancy tackling it yourself?

**Comment by djanosik** [comment]
Well, I'd like to submit a pull request, but the solution is not compilable. There are over 60 StyleCop issues that need to be fixed first.

**Comment by TrevorPilley** [comment]
There shouldn't be, what version of style cop do you have installed?

**Comment by djanosik** [comment]
The latest version (4.7.49). The issues are SA1642 (typo in documentation comment) and SA1210 (eg. `MicroLite.Characters` should be after `MicroLite.FrameworkExtensions` in `DeleteSqlBuilder.cs`).

**Comment by TrevorPilley** [comment]
I've just checked out the develop branch on a different machine to the one I usually use, I'm not seeing either of those come up. I'm using VS 2013, what are you using?

**Comment by djanosik** [comment]
VS 2015 RC. Are StyleCop rules culture-sensitive?

**Comment by TrevorPilley** [comment]
Yes, but the culture is set in the Settings.StyleCop file to en-GB - it could down to VS 2015 RC? I haven't installed that yet. Do you have a VS 2013 or VS 2012 install you could use instead?

**Comment by djanosik** [comment]
No, I don't have VS 2013 or 2012. It would be nice if you could update to VS 2015 (will go RTM on July 20th), DNX projects are far way better for developing libraries targeting multiple frameworks.

**Comment by TrevorPilley** [comment]
OK no problem, it's a small change so I can do it later today & push a new package to NuGet.

What are the benefits of a DNX project?

**Comment by djanosik** [comment]
Ok. What are the benefits? Well, at least you don't need to maintain multiple solution and project files. You can simply define target frameworks in `project.json`. Also you don't need any `.nuspec` files, because the output of DNX project compilation is not an assembly, but a NuGet package.

**Comment by TrevorPilley** [comment]
OK, the downside to that is that then no-one on VS 2013 or earlier can open the solution?

**Comment by djanosik** [comment]
Yes, of course. But you don't need Visual Studio to edit DNX projects.
