### ISSUE TITLE
dynamic table creation

### ISSUE THREAD

**Issue by elibyy** [TrevorPilley/MicroLite#396]
is it possible to create the model tables via the API? or i need to create an .sql file dependent on the driver?

**Comment by TrevorPilley** [comment]
You'll need to manage the scheme using something else, MicroLite doesn't support schema creation and updates, quite often they require more than a tool can generate.

Personally I use a combination of the RedGate tools to create scripts and DbUp to update a database. There are other sorts of migration tools you could look at or just manage .sql scripts yourself

**Comment by djanosik** [comment]
I suggest https://github.com/jonwagner/Insight.Database.Schema :)
