### ISSUE TITLE
Flattening of complex properties

### ISSUE THREAD

**Issue by djanosik** [TrevorPilley/MicroLite#405]
Hi,

does MicroLite support flattening of complex properties? Consider the following types.
```c#
public class Address
{
    public string Street { get; set; }

    public string City { get; set; }
}

public class Company 
{
    public long Id { get; set; }

    public Address Address { get; set; }
}
```
I would like to map the Address property to multiple columns:
```sql
CREATE TABLE Companies(
	Id bigint IDENTITY(1,1) NOT NULL,
	Address_Street nvarchar(200) NULL,
	Address_City nvarchar(200) NULL
)
```
Can we somehow modify how properties are mapped to columns?

**Comment by TrevorPilley** [comment]
No, not up to version 6.2.

Why do you want to do that? Surely addresses should be in their own table, a Company has an address but so can other things... in a normalized DB you would have:

Addresses PK AddressId
Companies PK CompanyId
CompanyAddresses FK CompanyId FK AddressId

**Comment by djanosik** [comment]
Of course, I just wanted to know whether there are other options. Thank you!
