### ISSUE TITLE
TypeConverter.ResolveActualType returns null

### ISSUE THREAD

**Issue by djanosik** [TrevorPilley/MicroLite#410]
The `TypeConverter.ResolveActualType` method assumes that a generic type is always a nullable value type. We have several tables with some columns containing JSON data (objects, arrays). As of now, we can't declare properties of type `IList<Type>` because it fails with NRE.

**Comment by TrevorPilley** [comment]
I don't see where the NRE is coming from, can you give me an example?

**Comment by djanosik** [comment]
When the `type` is `typeof(IList<string>)`, the line [172](https://github.com/TrevorPilley/MicroLite/blob/develop/MicroLite/TypeConverters/TypeConverter.cs#L172) in `TypeConverter.cs` will set `actualType` to `null`. It causes NRE somewhere the returned value is used.

**Comment by TrevorPilley** [comment]
Which method on the session are you calling?

**Comment by djanosik** [comment]
`session.InsertAsync(instance)`... here is the stack trace:
```
   at MicroLite.Mapping.ILGeneratorExtensions.EmitUnboxOrCast(ILGenerator ilGenerator, Type type)
   at MicroLite.Mapping.DelegateFactory.CreateInstanceFactory(IObjectInfo objectInfo)
   at MicroLite.Mapping.PocoObjectInfo..ctor(Type forType, TableInfo tableInfo)
   at MicroLite.Mapping.ConventionMappingConvention.CreateObjectInfo(Type forType)
   at MicroLite.Mapping.ObjectInfo.For(Type forType)
   at MicroLite.Core.AsyncSession.<InsertAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by TrevorPilley** [comment]
What is 'instance'?

**Comment by djanosik** [comment]
```c#
public class UserRow
{
    public long Id { get; set; }
    public long AccountId { get; set; }
    public string FullName { get; set; }
    public string DisplayName { get; set; }
    public string Email { get; set; }
    public IList<ContactDetail> ContactDetails { get; set; }
    public DateTime DateCreated { get; set; }
    public bool IsBlocked { get; set; }
}
```

**Comment by TrevorPilley** [comment]
The reason this isn't working is that MicroLite doesn't support collection properties as it doesn't do lazy loading, the idea with MicroLite is to use the include API to retrieve associated data so that you control exactly what data is loaded and when it is loaded.

**Comment by djanosik** [comment]
Well, it does. It supports collection properties. You only need to create your own `ITypeConverter`. When I change the property to be of non-generic collection type, ti works pretty well.
```c#
public ContactDetails ContactDetails { get; set; }
```
The whole collection is mapped to one column containing JSON data.

**Comment by TrevorPilley** [comment]
OK, what I meant was it doesn't natively support collections, you didn't mention you were using a custom `ITypeConverter`.

**Comment by djanosik** [comment]
Ok :) And I think it should work the same way with generic collection types. But it doesn't because of the NRE.

**Comment by TrevorPilley** [comment]
Yes, the code you mentioned is there to allow MicroLite to work with nullable struct properties (e.g. `public int? Numner { get; set; }` but it's also matching `IList<string>` in your case because it is a generic type however the call to `Nullable.GetUnderlyingType(type)` is where the null comes from because the `IList<T>` isn't a `Nullable<T>`.

Do you want to have a go at fixing it and sending a pull request?

**Comment by djanosik** [comment]
I want, but I haven't a chance yet to figure out what is wrong with StyleCop. https://github.com/TrevorPilley/MicroLite/issues/395

**Comment by TrevorPilley** [comment]
No worries, I haven't upgraded to VS 2015 yet so when I do I'll see if theres something odd going on with StyleCop

**Comment by TrevorPilley** [comment]
I've just pushed a beta of MicroLite 6.2.5 to [nuget](https://www.nuget.org/packages/MicroLite/6.2.5-beta) - let me know if that fixes your problem and I'll push it as a full release.

**Comment by djanosik** [comment]
Thank you, it's fixed.

**Comment by TrevorPilley** [comment]
Excellent, re-publish 6.2.5 as a non beta package later
