### ISSUE TITLE
Thoughts on OData queries

### ISSUE THREAD

**Issue by djanosik** [TrevorPilley/MicroLite#413]
One of reasons why I've decided to use MicroLite is the support for OData queries. We use them a lot in our applications. However there are two things I find disappointing about MicroLite's OData support.

1. It's built around the `SqlBuilder`. I think it will always be somehow limited when compared to writing queries in SQL. For example: you can't create efficient query for `SingleAsync` method; you can't select from TVF; etc. Yes, it can be fixed, but that's not the point. It should be possible to use OData queries with "every" SQL query you can imagine :)

2. It's tied to WebAPI extensions. I think it should be available to everyone, not just to users who choose to build their controllers on top of the `MicroLiteODataApiController`.

So, I am thinking about something like this:

```c#
public async Task<IOData<Record>> GetRecords(ODataQueryOptions<Record> odata)
{
    var query = new ODataQuery(
        "SELECT * FROM Whateever WHERE Id > @p0 AND @odata",
        10245, odata
    );

    return await session.ODataAsync<Record>(query);
}
```
- The `ODataQuery` is derived from `SqlQuery`. It transforms the `@odata` parameter to other `WHERE` and `ORDER BY` clauses. It has some limitations, but it might work.

- The `ODataAsync` method will execute information provided by the `ODataQuery`. It will make sure that the returned result conforms to the OData query. It will take into account parameters like `inlinecount`, etc.

What do you think?

**Comment by TrevorPilley** [comment]
One of the things I'd like to do around the WebApi stuff and OData stuff is to move it ahead on top of ASP.NET vNext and part of that would be moving away from the base MicroLiteApiController.

**Comment by TrevorPilley** [comment]
What I expect we will end up doing is replacing the MicroLite.Extensions.WebApi and MicroLite.Extensions.Mvc projects with a new MicroLite.Extensions.AspNet project which contains extensions for MicroLite for ASP.NET vNext (which is a single implementation for MVC and WebApi).

**Comment by djanosik** [comment]
Of course, it's obvious that you can't put an OData query string into an SQL command. They are not compatible in that way. What I want to say is that it doesn't really matter where the "translation" happens (in my `ODataQuery` or somewhere else). But it would be nice to have better control on what the SQL query will look like. As of now it's not possible to use OData query when selecting from TVF.

This is something I need to address and my proposed example might be one of possible ways.

**Comment by TrevorPilley** [comment]
What do you mean by TVF?

**Comment by djanosik** [comment]
TVF means Table-Valued Function.

**Comment by TrevorPilley** [comment]
If you override the `CreateSqlQuery` method, does that give you the control you want for now?

**Comment by djanosik** [comment]
Yes, but it would be an ugly non-reusable solution. I would need to do something like this:
```c#
protected override SqlQuery CreateSqlQuery(ODataQueryOptions queryOptions)
{
        var sqlQuery = queryOptions.CreateSqlQuery<TEntity>();

        return new SqlQuery(
                sqlQuery.CommandText.Replace("FROM Table", "FROM Function('param')"),
                sqlQuery.Arguments.ToArray()
        );
}
```
Well, that's not an option. I am already on ASP.NET vNext :)  But don't worry about that, I can find a solution. I just wanted to start a discussion about possible changes in OData support.

**Comment by TrevorPilley** [comment]
OK lets pick the OData side of things up when we start making the ASP.NET vNext extension for MicroLite 7, in the interim, you could raise a separate issue to add support for mapping an entity to a Table-Valued Function if that is actually what you want?

**Comment by TrevorPilley** [comment]
Actually, it wouldn't be as ugly as that, `CreateSqlQuery<T>` is an internal extension method but it uses the filter binders in the library which are all public so you could create your own binder for Select and then re-use the order and filter ones

**Comment by djanosik** [comment]
So far I've created a prototype of an easy to use OData4 [parser](https://github.com/djanosik/Moon.Libraries/tree/master/src/Moon.OData) based on the official [OData](https://github.com/OData/odata.net/) library. And a corresponding [model binder](https://github.com/djanosik/Moon.AspNet/tree/master/src/Moon.AspNet.OData) for ASP.NET vNext.
