### ISSUE TITLE
Add some helper convention mappings

### ISSUE THREAD

**Issue by TrevorPilley** [TrevorPilley/MicroLite#422]
In addition to `ConventionMappingSettings.Default`, add the following:

* `ConventionMappingSettings.LowercaseWithUnderscores`
* `ConventionMappingSettings.UppercaseWithUnderscores`

**Comment by mixerp** [comment]
This is a great idea. :+1:

**Comment by mixerp** [comment]
Not only this would be useful for PostgreSQL Server, but also for other DBMSes which are case sensitive such as Oracle and DB2.
