### ISSUE TITLE
ISessionFactory and multi-tetant web application

### ISSUE THREAD

**Issue by mixerp** [TrevorPilley/MicroLite#423]
We are using PetaPoco right now. Since it has become old, we are investigating newer MicroORMs like MicroLite.

Reading the MicroLite documentation, I understand that I need to configure the connection session factory `ISessionFactory` in advance and use it throughout the application lifetime. So, configuring the factory `Configure.Fluently().ForConnection().CreateSessionFactory()` during startup indicates that we can communicate with only one database per application instance.

Forgive me if I missed something in the documentation, but I could not find a recommended way to achieve this. Since our solution is multi-tenant, we do not have a single database to fire the query and perform DML operations.

Could you please point to me to the right direction?

**Comment by TrevorPilley** [comment]
You can create a number of different session factories and then open a session for whichever one you need.

The [blog](https://microliteorm.wordpress.com/2012/11/15/targeting-multiple-databases/) has a post regarding this

**Comment by TrevorPilley** [comment]
The way I generally do this myself is to register the session factories in [Ninject](http://www.ninject.org/) and then bind the session based upon which controller I am using:

```csharp
internal static class MicroLiteConfig
{
    internal static ISessionFactory DatabaseA { get; private set; }
    internal static ISessionFactory DatabaseB { get; private set; }
    internal static ISessionFactory DatabaseC { get; private set; }

    internal static void ConfigureConnections()
    {
        DatabaseA = Configure.Fluently().ForMsSql2005Connection("DatabaseA").CreateSessionFactory();
        DatabaseB = Configure.Fluently().ForMsSql2005Connection("DatabaseB").CreateSessionFactory();
        DatabaseC = Configure.Fluently().ForMsSql2005Connection("DatabaseC").CreateSessionFactory();
    }

    internal static void ConfigureExtensions()
    {
        ...
    }
}

public static class NinjectWebCommon
{
    ...

    private static void RegisterServices(IKernel kernel)
    {
        // Use DatabaseB for some specific controllers
        kernel.Bind<IAsyncSession>()
            .ToMethod(_ => MicroLiteConfig.DatabaseB.OpenAsyncSession())
            .WhenInjectedExactlyInto(typeof(Api.Controllers.OneController), typeof(Api.Controllers.TwoController))
            .InRequestScope();

        // Use DatabaseC for some specific controllers
        kernel.Bind<IAsyncSession>()
            .ToMethod(_ => MicroLiteConfig.DatabaseC.OpenAsyncSession())
            .WhenInjectedExactlyInto(typeof(Api.Controllers.SomeOtherController))
            .InRequestScope();

        // Use DatabaseA for all other controllers
        kernel.Bind<IAsyncReadOnlySession>()
            .ToMethod(_ => MicroLiteConfig.DatabaseA.OpenAsyncReadOnlySession())
            .InRequestScope();

        kernel.Bind<IAsyncSession>()
            .ToMethod(_ => MicroLiteConfig.DatabaseA.OpenAsyncSession())
            .InRequestScope();
    }
}
```

You should be able to use this approach with any IOC container.

**Comment by mixerp** [comment]
Hi, thank you for the response.

The problem with this approach is that you have to create `N` number of factories. In our case, we want to be able to support several database (tens to hundreds) without knowing the database name in advance and without touching the source code.

**Comment by TrevorPilley** [comment]
Ah OK, in that case the [Dynamic Connection Strings](https://microliteorm.wordpress.com/2014/12/15/microlite-6-0-dynamic-connection-strings/) may be of use.

**Comment by mixerp** [comment]
I am already aware that MicroLite supports passing connection string in a parameter. My only concern is if there is a disadvantage to to configure ISessionFactory for each request?

If you recommend this approach, we are definitely going to use MicroLite.

**Comment by TrevorPilley** [comment]
If you don't know the details until run-time then that's the only way to do it.

MicroLite internally will only create a single `ISessionFactory` per connection, once one exists it will be re-used even if you call `Configure.Fluently().For...Connection(...).CreateSessionFactory()` multiple times with the same parameters.

**Comment by mixerp** [comment]
So, this is a good news for me. Many thanks.

**Comment by mixerp** [comment]
One obvious question

`MicroLite internally will only create a single ISessionFactory per connection`

Does not `multiple databases` imply multiple connection?

**Comment by mixerp** [comment]
If I understand correctly, whenever MicroLite finds a new connection string, a new instance of `ISessionFactory` is created for each unique connection string. Is that right?

**Comment by TrevorPilley** [comment]
Yes, for every unique connection name, a single Session Factory will be created:

    var sf1 = Configure.Fluently().ForConnection("Database1").CreateSessionFactory();
    var sf2 = Configure.Fluently().ForConnection("Database1").CreateSessionFactory();

`sf1` and `sf2` will both be references to the same `ISessionFactory` instance.

    var sf1 = Configure.Fluently().ForConnection("Database1").CreateSessionFactory();
    var sf2 = Configure.Fluently().ForConnection("Database2").CreateSessionFactory();

`sf1` and `sf2` will be references to different `ISessionFactory` instances

Does that make sense?

**Comment by mixerp** [comment]
Yes, makes a perfect sense. +1
