### ISSUE TITLE
SqlAzure

### ISSUE THREAD

**Issue by venantvr** [TrevorPilley/MicroLite#439]
Are there any known issues when using MicroLite on SqlAzure ?

We encounter some strange behaviors that are a bit disturbing : when auditing the database, we monitor that our queries are handled by the server in a very good way (50ns). However, the "rpc completed" events arrive in times that are thousands times the delay they should be... 500 000ns. We do not have such issues when using Entity Framework on this server.

**Comment by TrevorPilley** [comment]
I haven't used it against SqlAzure but no-one else has raise anything along those lines... There isn't any special code in the library specifically for SqlAzure - as far as I know, it just looks like SQL 2008 R2.

Is there anything specific you can do to reproduce the problem you are seeing?

**Comment by venantvr** [comment]
Thanks for your answer.

Update operations are good. This problem occurs on Insert operations. According to the DBA, it sounds like the "response" to the client (the PK) is slowed down by something we don't identify (lame transaction, network... ?) On the mapping side, our object identity uses the DBGenerated strategy. We are able to reproduce this with a Console App that commits simple Inserts on a dummy table. For the clarity of the test, we do not use any transaction. The same problem occurs when calling a storeproc to manage the Insert. We'll look forward to this and come back to you after some more investigations.

**Comment by venantvr** [comment]
Ok, we now have some good elements of response : http://stackoverflow.com/questions/35231430/why-does-azure-database-perform-better-with-transactions

Many thanks, let me know if you have any questions.
