### ISSUE TITLE
Incorrect parameter numbers when using SqlUtility.RenumberParameters

### ISSUE THREAD

**Issue by TrevorPilley** [TrevorPilley/MicroLite#443]
`SqlUtility.RenumberParameters("SELECT * FROM [Table1] WHERE [Column1] >= @p0 AND [Column2] <= @p1 AND [Column3] = @p2", totalArgumentCount: 13);`

should return

`SELECT * FROM [Table1] WHERE [Column1] >= @p10 AND [Column2] <= @p11 AND [Column3] = @p12`

but returns

`SELECT * FROM [Table1] WHERE [Column1] >= @p10 AND [Column2] <= @p11 AND [Column3] = @p112`

---

`SqlUtility.RenumberParameters("SELECT * FROM [Table1] WHERE [Column1] >= @p0 AND [Column2] <= @p1 AND [Column3] IN(@p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20) AND [Column4] = @p21", totalArgumentCount: 13);`

should return

`SELECT * FROM [Table1] WHERE [Column1] >= @p3 AND [Column2] <= @p4 AND [Column3] IN(@p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23) AND [Column4] = @p24`

but returns

`SELECT * FROM [Table1] WHERE [Column1] >= @p3 AND [Column2] <= @p4 AND [Column3] IN(@p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23) AND [Column4] = @p21`

---

`SqlUtility.RenumberParameters("SELECT * FROM [Table1] WHERE [Column1] >= @p0 AND [Column2] <= @p1 AND [Column3] IN(@p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20) AND [Column4] = @p21;", totalArgumentCount: 13);`

should return

`SELECT * FROM [Table1] WHERE [Column1] >= @p3 AND [Column2] <= @p4 AND [Column3] IN(@p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23) AND [Column4] = @p24;`

but returns

`SELECT * FROM [Table1] WHERE [Column1] >= @p3 AND [Column2] <= @p4 AND [Column3] IN(@p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23) AND [Column4] = @p21;`

**Comment by jezza323** [comment]
I have just come across this one again in 6.3.2

This was the command text generated for 3 queries run as includes with 4 parameters each (12 total)

`SELECT N.*
                                    FROM dbo.ref_KalibreNewsItem N
                                    LEFT JOIN dbo.ref_KalibreNewsSubscription S ON N.SiteId = S.SiteId AND S.Username = @p0 AND N.IsCurrent
                                    LEFT JOIN dbo.ref_KalibreNewsItemAcknowledgement A ON A.NewsId = N.Id AND N.IsCurrent
                                    WHERE (N.SiteId IS NULL OR S.Id IS NOT NULL) 
                                        AND N.IsCurrent = 1
                                        AND A.Id IS NULL
                                        AND (N.MessageDate IS NULL OR DATEADD(MINUTE, @p1, N.MessageDate) > @p3) 
                                        AND (N.ClosedAt IS NULL OR DATEADD(MINUTE, @p2, N.ClosedAt) > @p3);
SELECT N.*
                                    FROM dbo.ref_KalibreNewsItem N
                                    LEFT JOIN dbo.ref_KalibreNewsSubscription S ON N.SiteId = S.SiteId AND S.Username = @p4 AND N.IsCurrent
                                    LEFT JOIN dbo.ref_KalibreNewsItemAcknowledgement A ON A.NewsId = N.Id AND N.IsCurrent
                                    WHERE (N.SiteId IS NULL OR S.Id IS NOT NULL) 
                                        AND N.IsCurrent = 1
                                        AND A.Id IS NOT NULL
                                        AND (N.MessageDate IS NULL OR DATEADD(MINUTE, @p5, N.MessageDate) > @p7) 
                                        AND (N.ClosedAt IS NULL OR DATEADD(MINUTE, @p6, N.ClosedAt) > @p7);
SELECT N.*
                                    FROM dbo.ref_KalibreNewsItem N
                                    LEFT JOIN dbo.ref_KalibreNewsSubscription S ON N.SiteId = S.SiteId AND S.Username = @p8 AND N.IsCurrent
                                    LEFT JOIN dbo.ref_KalibreNewsItemAcknowledgement A ON A.NewsId = N.Id AND N.IsCurrent
                                    WHERE (N.SiteId IS NULL OR S.Id IS NOT NULL) 
                                        AND N.IsCurrent = 1
                                        
                                        AND (N.MessageDate IS NULL OR DATEADD(MINUTE, @p9, N.MessageDate) > @p11) 
                                        AND (N.ClosedAt IS NULL OR DATEADD(MINUTE, @p2, N.ClosedAt) > @p11)`

**Comment by TrevorPilley** [comment]
I suspect this is related to the parameter names being effectively out of sequence in the SQL statement, that shouldn't affect it but seems to so I'll have to dig into it a bit further.

**Comment by jezza323** [comment]
The tests I added have some out of order and some in order but repeated

**Comment by TrevorPilley** [comment]
I don't think repeated is an issue unless they are out of order, e.g. this works as expected:

```
var commandText = SqlUtility.RenumberParameters("(Column1 = @p0 OR @p0 IS NULL) AND Column2 = @p1", totalArgumentCount: 12);
Assert.Equal("(Column1 = @p10 OR @p10 IS NULL) AND Column2 = @p11", commandText);
```

I'll look into why the sequence seems to matter as I'm not sure how that's causing an issue at the moment...

**Comment by TrevorPilley** [comment]
FYI, the last test you added `ReNumberParametersWithExistingArgumentsWithThreeColonPrefixAndARepeatedValueAndMoreThanPrefixCharacter` isn't going to work anyway as the expected string is quite different from the input (different spacing and different parameter names)...

**Comment by TrevorPilley** [comment]
I'll push 6.3.3 to nuget this evening.

**Comment by jezza323** [comment]
Thanks Trevor
