### ISSUE TITLE
Loading child entities

### ISSUE THREAD

**Issue by ma499** [TrevorPilley/MicroLite#451]
What is the easiest way of loading child entities using MicroLite?

The example I have is a 'Cases' table with a 'Visitors' table. One Case has many Visitors. I am modelling this in my application with a Case class that contains, as a property a List<Visitor>.

**Comment by TrevorPilley** [comment]
MicroLite is a Micro ORM so doesn't support relationships at an entity level.

The approach MicroLite takes is to allow you to specify the data you want at the time you need it and to reduce the number of queries and connections you can leverage the [Include API](https://github.com/TrevorPilley/MicroLite/wiki#include) in your View Model/Controller to collate the data needed at that point in the application
