### ISSUE TITLE
Whole Process crashes with AccessViolationException when assigning a non-null value to a nullable Property while using ITypeConverter

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [TrevorPilley/MicroLite#455]
PR with a failing unit test & fix: https://github.com/TrevorPilley/MicroLite/pull/456

Judging how it can crash the process depending on data this is really critical.

**Comment by TrevorPilley** [comment]
Based upon the code in your PRs, I couldn't get this to throw the exception you specified, however I was able to update your test so that the value wasn't correct without the change you proposed in the DelegateFactory so I've pulled it and tweaked it

**Comment by TrevorPilley** [comment]
This is now available on nuget.org as 6.3.2

**Comment by slawomir-brzezinski-at-interxion** [comment]
Perhaps the reason why this didn't crash for you is because we're using the 4.5.X version (from `MicroLite.NET45.sln` ).

If I check out fac2f7d2889afdfe7c2f7b3c0e88b91925d95516 (this is branched off the 6.2.0 version that we are using but it also fails with master & develop), I get the very AccessViolationException on my and other dev machines.

In either case [this change](https://github.com/TrevorPilley/MicroLite/blame/develop/MicroLite/Mapping/DelegateFactory.cs#L250) is what fixes the situation so thanks for pulling it in.
