### ISSUE TITLE
Where is IReadOnlySession

### ISSUE THREAD

**Issue by timk00** [TrevorPilley/MicroLite#459]
My apologies for posting a question here.  I didn't find a way to ask this kind of question.

I cloned the source yesterday and I cannot find any of the non-async session code.

Where should I be looking?

Thanks

**Comment by TrevorPilley** [comment]
You're probably looking at the develop branch which is where I'm working on the async only code and the move to .NET Core, have a look at the 6.3.x branch where the currently released code lives

**Comment by timk00** [comment]
That was it.
Thanks.
And thanks for a great library.
