### ISSUE TITLE
No way to cleanly close pooled connections (PostgresQL)

### ISSUE THREAD

**Issue by wwoods** [TrevorPilley/MicroLite#471]
MicroLite's SessionFactory seems to pool connections, which is great, except when I want to write a bit of test code that recreates my database.  Currently, my workaround is to kill (pg_terminate_backend) connections to the database, but then subsequent MicroLite queries may fail due to a closed transport channel.  Is there a clean way to do this already that I'm missing?

**Comment by TrevorPilley** [comment]
There's no explicit connection pooling done by MicroLite, are you disposing of sessions when you no longer need them? E.g. In a using or via an IOC container?

**Comment by wwoods** [comment]
Right, the pooling is in Npgsql, I suppose this issue is about being unable to access that pool functionality through MicroLite to close the connections.  Is there a way through a MicroLite `ISession` to get to the underlying `NpgsqlConnection`?  Apparently that object has a means of closing all pooled connections: https://stackoverflow.com/questions/9033356/connection-still-idle-after-close#comment76334221_9033410  Or is there some other way of accessing the underlying Npgsql objects?

**Comment by TrevorPilley** [comment]
The post you linked to offers 2 suggestions, disabling pooling via the connection string or calling NpgsqlConnection.ClearAllPools(), if that method is static you can call it directly.

You can't get at the NpgSqlConnection directly, it's created in when you call ISessionFactory.OpenSession() and closed & disposed when you call ISession.Dispose()

**Comment by wwoods** [comment]
Ah, yes, you're right, I failed to notice it was a static method.  Thank you!
