### ISSUE TITLE
Session instances not thread safe - caused by reuse of DbCommand

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [TrevorPilley/MicroLite#472]
**Synopsis**
A code in the project we are maintaining fires multiple read-only [`AsyncReadOnlySession.SingleAsync`](https://github.com/TrevorPilley/MicroLite/blob/3bd186dec8362799d3d3ee9d60f57785fa0837ce/MicroLite/Core/AsyncReadOnlySession.cs#L271) queries in parallel, which, only after some time, revealed that the whole `AsyncReadOnlySession` is not thread safe to allow that, because it [reuses the `DbCommand`](https://github.com/TrevorPilley/MicroLite/blob/3bd186dec8362799d3d3ee9d60f57785fa0837ce/MicroLite/Core/AsyncReadOnlySession.cs#L333) object.

**Discovery:**
For our case, with MS Sql Server, the failure is:

`MicroLite.MicroLiteException: The command execution cannot proceed due to a pending asynchronous operation already in progress. ---> System.InvalidOperationException: The command execution cannot proceed due to a pending asynchronous operation already in progress.`

We were lead to the conclusion by [this StackOverflow](https://stackoverflow.com/questions/3992811/performing-an-sql-query-while-waiting-on-an-asyncronous-operation-generates-an-e/3993493#3993493), which has the exact same error due to reusing the DbCommand object.

**Severity:**
In our case we received an error from the database driver, but this can cause much more serious problems, e.g. a thread can get its query replaced before execution, which can potentially even succeed with untruthful data.

**Resolution?**
Is a fix to this something you would rather drive yourself? If not, can you just advise the general direction?
I guess a new command should be created for each query, but this will require some refactor around things like the [`ConfigureCommand`](https://github.com/TrevorPilley/MicroLite/blob/3bd186dec8362799d3d3ee9d60f57785fa0837ce/MicroLite/Core/SessionBase.cs#L140)

**Comment by TrevorPilley** [comment]
Hi, the session objects are intentionally not thread safe, the documentation states that. The reuse of the dbcommand is to reduce memory usage and improve performance when performing the same query with different identifiers in the same session instance.

To resolve your issue, you will either need to do an await before reusing the session instance or look at the includes feature. The includes feature is designed for efficient fetching of multiple values.

**Comment by slawomir-brzezinski-at-interxion** [comment]
@TrevorPilley I must say I couldn't find any mention in the docs. I've scanned all the [wiki pages](https://github.com/TrevorPilley/MicroLite/wiki) for word 'thread', I've checked [docs on the interface I use](https://github.com/TrevorPilley/MicroLite/blob/develop/MicroLite/IAsyncReadOnlySession.cs#L24), I've [grepped code for the word thread](https://github.com/TrevorPilley/MicroLite/search?utf8=%E2%9C%93&q=thread&type=) and I can't see anything.  

This probably answers why developers in our project went ahead with the parallel code, so I think it's a sign to make it more prominent. IMHO it should definitely be mentioned in the quick start, as this is often all that developers end up reading, and, by necessity mark all the non-thread sessions in the type docs (e.g. [like this](https://stackoverflow.com/questions/4540290/how-to-tag-that-a-class-is-thread-safe-or-not/15169273#15169273)).

**Comment by taliesins** [comment]
I think that the lack of thread safety is a far more important then a micro optimization of sql command re-usage (maybe it would be worth it if prepare was used). There is hardly any difference in performance. Just spin up a new sql connection and sql command when you need it. .NET is pretty good with short lived objects. Connection pooling will provide you with all the needed performance required. 

https://stackoverflow.com/questions/4621261/is-it-better-to-reuse-sqlcommand-when-executing-the-same-sql-query-several-times

https://stackoverflow.com/questions/5981376/is-it-better-to-execute-many-sql-commands-with-one-connection-or-reconnect-ever

Looks like we are not rely using the prepare command anywhere: 
https://github.com/TrevorPilley/MicroLite/search?utf8=%E2%9C%93&q=prepare&type=

**Comment by slawomir-brzezinski-at-interxion** [comment]
I second that @taliesins . Thread unsafety is very insidious and almost never sought for by developers, even despite documentation.

@TrevorPilley if you want to stick to the micro-optimization, You should use a pool of 'exclusive use' command objects, which produces more commands as needed (you could also give it a max count, not to inflate it indefinitely, which, when exceeded, would just dispose the commands returned to it).
